# Generated by Django 5.1.6 on 2025-02-27 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('location', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('size_filled', models.FloatField(blank=True, default=0, null=True)),
                ('total_sections', models.IntegerField(blank=True, default=0, null=True)),
                ('total_racks', models.IntegerField(blank=True, default=0, null=True)),
                ('warehouse_create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.FloatField()),
                ('total_racks', models.IntegerField(default=0)),
                ('is_filled', models.BooleanField(default=False)),
                ('size_filled', models.FloatField(blank=True, default=0, null=True)),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplysyncapi.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack_id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.FloatField()),
                ('total_products', models.IntegerField(blank=True, default=0, null=True)),
                ('size_filled', models.FloatField(blank=True, default=0, null=True)),
                ('is_filled', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplysyncapi.section')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplysyncapi.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('product_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot_space', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplysyncapi.rack')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplysyncapi.warehouse')),
            ],
        ),
    ]
