# Generated by Django 5.1.6 on 2025-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='total_products',
            field=models.IntegerField(null=True),
        ),
    ]
