# Generated by Django 5.1.6 on 2025-02-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0003_productlot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='total_products',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
