# Generated by Django 5.1.6 on 2025-02-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0005_warehouse_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
    ]
