# Generated by Django 5.1.6 on 2025-02-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0006_section_is_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='percent_filled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='percent_filled',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='size',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='total_racks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='total_sections',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='percent_filled',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
