# Generated by Django 5.1.6 on 2025-02-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0007_rack_percent_filled_section_percent_filled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='percent_filled',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='total_products',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='percent_filled',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='total_racks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='percent_filled',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='total_racks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='total_sections',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
