# Generated by Django 5.1.6 on 2025-02-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0008_alter_rack_percent_filled_alter_rack_total_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='percent_filled',
            new_name='size_filled',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='percent_filled',
            new_name='size_filled',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='percent_filled',
            new_name='size_filled',
        ),
    ]
