# Generated by Django 5.1.6 on 2025-02-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0009_rename_percent_filled_rack_size_filled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='profile_create_time',
            new_name='warehouse_create_time',
        ),
    ]
