# Generated by Django 5.1.6 on 2025-02-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplysyncapi', '0010_rename_profile_create_time_warehouse_warehouse_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlot',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
