# Generated by Django 5.0.4 on 2024-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_section_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='section',
            name='identifier',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='identifier',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
