# Generated by Django 5.0.4 on 2024-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_section_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='identifier',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='rack_identifier',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='section',
            name='section_identifier',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
