# Generated by Django 5.0.4 on 2024-08-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_id_remove_rack_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='section',
            new_name='section_identifier',
        ),
    ]
