# Generated by Django 5.0.4 on 2024-08-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_section_rack_section_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='product',
            new_name='product_id',
        ),
    ]
