# Generated by Django 5.0.4 on 2024-08-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_product_rack_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
